### ISSUE TITLE
How to export tet-mesh?

### ISSUE THREAD

**Issue by SophusDavid** [nv-tlabs/FlexiCubes#12]
thanks for your awesome work!
I noticed that in your paper you claim that flexicubes can extend to tet-mesh .I am interested in this .Could you tell me how to export a tet-mesh with flexicubes?

In flexicubes.py , the class of FlexiCubes there is a option to export tetmesh :
``` 
def __call__(self, x_nx3, s_n, cube_fx8, res, beta_fx12=None, alpha_fx8=None,
                 gamma_f=None, training=False, output_tetmesh=False, grad_func=None): 
``` 

but when i turn on it and run the optimize.py ,I found the rasterize method for tet-mesh have not implemented yet.

``` def render_mesh(mesh, mv, mvp, iter_res, return_types = ["mask", "depth"], white_bg=False):
    v_pos_clip = xfm_points(mesh.vertices.unsqueeze(0), mvp)  # Rotate it to camera coordinates
    rast, db = dr.rasterize(
        dr.RasterizeGLContext(), v_pos_clip, mesh.faces.int(), iter_res)
```

this caused the error in nvdiffrast.
```
def rasterize(glctx, pos, tri, resolution, ranges=None, grad_db=True):
```

So  how can i export and optimize a tet-mesh .

looking forward to some advise .

**Comment by frankshen07** [comment]
Hi @SophusDavid, the example we provided is not intended for tetmesh. You can first optimize using the triangular mesh, and once the shape is optimized, extract the tetrahedral mesh with output_tetmesh=True and then dump out the results. The triangular mesh and tetrahedral mesh would represent the same geometry since they are parametrized by the same field.

**Comment by seanxzhan** [comment]
Hi @frankshen07 , I ran `optimize.py`, and after 1000 iterations I also output the tetmesh (with `output_tetmesh=True`). The triangle mesh has converged, but the tetmesh looks like this. Do you know what could have gone wrong? Is there a way to train Flexicubes with tetmesh (render tetmesh during training)? 

In the paper, Section 4.5 says "We augment FlexiCubes to additionally output a tetrahedral mesh when desired, which exactly conforms to the boundary of the extracted surface and supports automatic differentiation in the same sense as our surface extraction." So it sounds like there's a way to have the tetmesh conform to the trimesh. 

<img width="620" alt="broken_tetmesh" src="https://github.com/user-attachments/assets/e10f03e0-21b4-4b3b-a863-38dd782a831f">

**Comment by frankshen07** [comment]
Hi @seanxzhan, 

Thank you for reporting this issue. The problem is caused by a bug in the current published version of the code. Could you please try replacing the code at [lines 464-465](https://github.com/nv-tlabs/FlexiCubes/blob/241bf4927e53f59e55da5e5818dbb9359010b8cb/flexicubes.py#L464-L465) with the following:

```python
quad_vd_idx[flip_mask] = quad_vd_idx[flip_mask][:, [0, 1, 3, 2]]
quad_vd_idx[~flip_mask] = quad_vd_idx[~flip_mask][:, [2, 3, 1, 0]]

This should fix your problem, and we will update the code shortly.

**Comment by seanxzhan** [comment]
Hi @frankshen07 , thank you for your help! It works now! 

![image](https://github.com/user-attachments/assets/d47b8acc-a589-4411-b8bd-6cbd835fe5f3)
